# <span style="color:blue;font-weight:bold;font-size:1.1em">Homework 2: Arrays, Table Manipulation, and Visualization</span>

In [29]:
# Don't change this cell; just run it.
# When you log-in please hit return (not shift + return) after typing in your email
import numpy as np
from datascience import *

# These lines do some fancy plotting magic.\n",
import matplotlib
%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

**Recommended Reading**: 
* [Data Types](https://www.inferentialthinking.com/chapters/04/data-types.html) 
* [Sequences](https://www.inferentialthinking.com/chapters/05/sequences.html)
* [Tables](https://www.inferentialthinking.com/chapters/06/tables.html)

Please complete this notebook by filling in the cells provided.
Throughout this homework and all future ones, please be sure to not re-assign variables throughout the notebook! For example, if you use `max_temperature` in your answer to one question, do not reassign it later on.

Before continuing the assignment, select "Save and Checkpoint" in the File menu.

## <span style="color:blue;font-weight:bold;font-size:1.1em">1. Creating Arrays</span>

**Question 1.** Make an array called `weird_numbers` containing the following numbers (in the given order):

1. -2
2. the sine of 1.2
3. 3
4. 5 to the power of the cosine of 1.2

*Hint:* `sin` and `cos` are functions in the `np` module.

*Note:* Python lists are different/behave differently than numpy arrays. In Intro Stats, we use numpy arrays, so please make an **array**, not a python list.

<!--
BEGIN QUESTION
name: q1_1
-->

In [2]:
# Our solution involved one extra line of code before creating
# weird_numbers.

weird_numbers = ...
weird_numbers

array([-2.        ,  0.93203909,  3.        ,  1.79174913])

**Question 2.** Make an array called `numbers_in_order` using the `np.sort` function.  

<!--
BEGIN QUESTION
name: q1_2
-->

In [3]:
numbers_in_order = ...
numbers_in_order

array([-2.        ,  0.93203909,  1.79174913,  3.        ])

**Question 3.** Find the mean and median of `weird_numbers` using the `np.mean` and `np.median` functions.  

<!--
BEGIN QUESTION
name: q1_3
-->

In [4]:
weird_mean = ...
weird_median = ...

# These lines are provided just to print out your answers.
print('weird_mean:', weird_mean)
print('weird_median:', weird_median)

weird_mean: 0.930947052911
weird_median: 1.36189410582

## <span style="color:blue;font-weight:bold;font-size:1.1em">2. Indexing Arrays</span>

These exercises give you practice accessing individual elements of arrays.  In Python (and in many programming languages), elements are accessed by *index*, so the first element is the element at index 0.

*Note:* Please don't use bracket notation when indexing (i.e. `arr[0]`), as this can yield different data type outputs than what we will be expecting.

**Question 1.** The cell below creates an array of some numbers.  Set `third_element` to the third element of `some_numbers`.

<!--
BEGIN QUESTION
name: q2_1
-->

In [5]:
some_numbers = make_array(-1, -3, -6, -10, -15)

third_element = ...

third_element

-6

**Question 2.** The next cell creates a table that displays some information about the elements of `some_numbers` and their order.  Run the cell to see the partially-completed table, then fill in the missing information (the cells that say "Ellipsis") by assigning `blank_a`, `blank_b`, `blank_c`, and `blank_d` to the correct elements in the table.

<!--
BEGIN QUESTION
name: q2_2
-->

In [28]:
blank_a = '- -'
blank_b = '- -'
blank_c = ...
blank_d = ...

elements_of_some_numbers = Table().with_columns(
    "English name for position", make_array("first", "second", blank_a, blank_b, "fifth"),
    "Index",                     make_array(blank_c, 1, 2, blank_d, 4),
    "Element",                   make_array(0, 10, 21, 32, 43)
)

elements_of_some_numbers

English name for position | Index    | Element
first                     | Ellipsis | 0
second                    | 1        | 10
- -                       | 2        | 21
- -                       | Ellipsis | 32
fifth                     | 4        | 43

**Question 3.** You'll sometimes want to find the *last* element of an array.  Suppose an array has 142 elements.  What is the index of its last element?

<!--
BEGIN QUESTION
name: q2_3
-->

In [7]:
index_of_last_element = ...

More often, you don't know the number of elements in an array, its *length*.  (For example, it might be a large dataset you found on the Internet.)  The function `len` takes a single argument, an array, and returns the `len`gth of that array (an integer).

**Question 4.** The cell below loads an array called `president_birth_years`.  Calling `.column(...)` on a table returns an array of the column specified, in this case the `Birth Year` column of the `president_births` table. The last element in that array is the most recent birth year of any deceased president. Assign that year to `most_recent_birth_year`.

<!--
BEGIN QUESTION
name: q2_4
-->

In [8]:
president_birth_years = Table.read_table("president_births.csv").column('Birth Year')
president_birth_years

array([1732, 1735, 1743, 1751, 1758, 1767, 1767, 1773, 1782, 1784, 1790,
       1791, 1795, 1800, 1804, 1808, 1809, 1822, 1822, 1829, 1831, 1833,
       1837, 1843, 1856, 1857, 1858, 1865, 1872, 1874, 1882, 1884, 1890,
       1908, 1911, 1913, 1913, 1917])

In [9]:
most_recent_birth_year = ...

most_recent_birth_year

1917

**Question 5.** Finally, assign `sum_of_birth_years` to the sum of the first, tenth, and last birth year in `president_birth_years`.

<!--
BEGIN QUESTION
name: q2_5
-->

In [10]:
sum_of_birth_years = ...
sum_of_birth_years

5433

## <span style="color:blue;font-weight:bold;font-size:1.1em">3. Basic Array Arithmetic</span>

**Question 1.** Multiply the numbers 42, 4224, 42422424, and -250 by 157. Assign each variable below such that `first_product` is assigned to the result of $42 * 157$, `second_product` is assigned to the result of $4224 * 157$, and so on. 

For this question, **don't** use arrays.

<!--
BEGIN QUESTION
name: q3_1
-->

In [16]:
first_product =...
second_product = ...
third_product = ...
fourth_product = ...

print(first_product, second_product, third_product, fourth_product)

Ellipsis Ellipsis Ellipsis Ellipsis

**Question 2.** Now, do the same calculation, but using an array called `numbers` and only a single multiplication (`*`) operator.  Store the 4 results in an array named `products`.

<!--
BEGIN QUESTION
name: q3_2
-->

In [15]:
numbers = ...
products = ...
products

Ellipsis

**Question 3.** Oops, we made a typo!  Instead of 157, we wanted to multiply each number by 1577.  Compute the correct products in the cell below using array arithmetic.  Notice that your job is really easy if you previously defined an array containing the 4 numbers.

<!--
BEGIN QUESTION
name: q3_3
-->

In [14]:
correct_products = ...
correct_products

Ellipsis

**Question 4.** We've loaded an array of temperatures in the next cell.  Each number is the highest temperature observed on a day at a climate observation station, mostly from the US.  Since they're from the US government agency [NOAA](noaa.gov), all the temperatures are in Fahrenheit.  Convert them all to Celsius by first subtracting 32 from them, then multiplying the results by $\frac{5}{9}$. Make sure to **ROUND** the final result after converting to Celsius to the nearest integer using the `np.round` function.

<!--
BEGIN QUESTION
name: q3_4
-->

In [13]:
max_temperatures = Table.read_table("temperatures.csv").column("Daily Max Temperature")

celsius_max_temperatures = ...

celsius_max_temperatures

Ellipsis

**Question 5.** The cell below loads all the *lowest* temperatures from each day (in Fahrenheit).  Compute the size of the daily temperature range for each day.  That is, compute the difference between each daily maximum temperature and the corresponding daily minimum temperature.  **Pay attention to the units, give your answer in Celsius!** Make sure **NOT** to round your answer for this question!

<!--
BEGIN QUESTION
name: q3_5
-->

In [12]:
min_temperatures = Table.read_table("temperatures.csv").column("Daily Min Temperature")

celsius_min_temperatures = ...
celsius_max_temperatures = ...

celsius_temperature_ranges = ...
celsius_temperature_ranges

Ellipsis

## <span style="color:blue;font-weight:bold;font-size:1.1em">4. Old Faithful</span>

Old Faithful is a geyser in Yellowstone that erupts every 44 to 125 minutes (according to [Wikipedia](https://en.wikipedia.org/wiki/Old_Faithful)). People are [often told that the geyser erupts every hour](http://yellowstone.net/geysers/old-faithful/), but in fact the waiting time between eruptions is more variable. Let's take a look.

**Question 1.** The first line below assigns `waiting_times` to an array of 272 consecutive waiting times between eruptions, taken from a classic 1938 dataset. Assign the names `shortest`, `longest`, and `average` so that the `print` statement is correct.

<!--
BEGIN QUESTION
name: q5_1
-->

In [16]:
waiting_times = Table.read_table('old_faithful.csv').column('waiting')

shortest = min(waiting_times)
longest = max(waiting_times)
average = np.mean(waiting_times)

print("Old Faithful erupts every", shortest, "to", longest, "minutes and every", average, "minutes on average.")

Old Faithful erupts every 43 to 96 minutes and every 70.8970588235 minutes on average.

**Question 2.** Assign `biggest_decrease` to the biggest decrease in waiting time between two consecutive eruptions. For example, the third eruption occurred after 74 minutes and the fourth after 62 minutes, so the decrease in waiting time was 74 - 62 = 12 minutes. We give you the differences under the name `differences`.

*Hint 1*: You'll need an array arithmetic function [mentioned in the textbook](https://www.inferentialthinking.com/chapters/05/1/arrays.html#Functions-on-Arrays). You have also seen this function earlier in the homework!

*Hint 2*: A difference is only a decrease, if the difference is negative.  Also, we want to return the absolute value of the biggest decrease.

<!--
BEGIN QUESTION
name: q5_2
-->

In [9]:
biggest_decrease = ...
biggest_decrease

Ellipsis

**Question 3.** Suppose that you *always* expected the next eruption to be exactly 60 minutes after the end of the current eruption.  We use an `np.repeat` to create the array of all 60's, use it to create an array called `difference_from_expected`.  


*Hint*: You'll need to compare a cumulative sum to a range. You'll go through `np.arange` more thoroughly in Lab 3, but you can read about it in this [textbook section](https://www.inferentialthinking.com/chapters/05/2/Ranges.html).

For example, since the first three waiting times are 79, 54, and 74, the total waiting time for 3 eruptions is 79 + 54 + 74 = 207. The expected waiting time for 3 eruptions is 60 * 3 = 180. Therefore, `difference_from_expected.item(2)` should be $|207 - 180| = 27$.

<!--
BEGIN QUESTION
name: q5_3
-->

In [8]:
expected = ...

difference_from_expected = ...
difference_from_expected

Ellipsis

**Question 4.** Compute the average `difference_from_expected`.  

<!--
BEGIN QUESTION
name: q5_4
-->

In [6]:
average_error = ...
average_error

Ellipsis

## <span style="color:blue;font-weight:bold;font-size:1.1em">5. Tables</span>

**Question 1.** Suppose you have 4 apples, 3 oranges, and 3 pineapples.  (Perhaps you're using Python to solve a high school Algebra problem.)  Create a table that contains this information.  It should have two columns: `fruit name` and `count`.  Assign the new table to the variable `fruits`.

**Note:** Use lower-case and singular words for the name of each fruit, like `"apple"`.

<!--
BEGIN QUESTION
name: q6_1
-->

In [37]:
# Our solution uses 1 statement split over 3 lines.
fruits = Table().with_columns('fruit name', make_array('apples', 'oranges', 'pineapples') , 'count', make_array(4,3,3))

fruits

fruit name | count
apples     | 4
oranges    | 3
pineapples | 3

**Question 2.** The file `inventory.csv` contains information about the inventory at a fruit stand.  Each row represents the contents of one box of fruit. Load it as a table named `inventory` using the `Table.read_table()` function. `Table.read_table(...)` takes one argument (data file name in string format) and returns a table.

<!--
BEGIN QUESTION
name: q6_2
-->

In [5]:
inventory = ...
inventory

Ellipsis

**Question 3.** Does each box at the fruit stand contain a different fruit? Set `all_different` to `True` if each box contains a different fruit or to `False` if multiple boxes contain the same fruit.

*Hint:* You don't have to write code to calculate the True/False value for `all_different`. Just look at the `inventory` table and assign `all_different` to either `True` or `False` according to what you can see from the table in answering the question.

<!--
BEGIN QUESTION
name: q6_3
-->

In [39]:
all_different = False
all_different

False

**Question 4.** The file `sales.csv` contains the number of fruit sold from each box last Saturday.  It has an extra column called "price per fruit (\$)" that's the price *per item of fruit* for fruit in that box.  The rows are in the same order as the `inventory` table.  Load these data into a table called `sales`.

<!--
BEGIN QUESTION
name: q6_4
-->

In [4]:
sales = ...

sales

Ellipsis

**Question 5.** How many fruits did the store sell in total on that day?

<!--
BEGIN QUESTION
name: q6_5
-->

In [2]:
total_fruits_sold = ...

total_fruits_sold

Ellipsis

**Question 6.** What was the store's total revenue (the total price of all fruits sold) on that day?

*Hint:* If you're stuck, think first about how you would compute the total revenue from just the grape sales.

<!--
BEGIN QUESTION
name: q6_6
-->

In [3]:
total_revenue = ...

total_revenue

Ellipsis

**Question 7.** Make a new table called `remaining_inventory`.  It should have the same rows and columns as `inventory`, except that the amount of fruit sold from each box should be subtracted from that box's count, so that the "count" is the amount of fruit remaining after Saturday.

<!--
BEGIN QUESTION
name: q6_7
-->

In [1]:
new_count = ...

remaining_inventory = ...

remaining_inventory

Ellipsis

Below we load tables containing 200,000 weekday Uber rides in the Manila, Philippines, and Boston, Massachusetts metropolitan areas from the [Uber Movement](https://movement.uber.com) project. The `sourceid` and `dstid` columns contain codes corresponding to start and end locations of each ride. The `hod` column contains codes corresponding to the hour of the day the ride took place. The `ride time` column contains the length of the ride, in minutes.

In [ ]:
boston = Table.read_table("boston.csv")
manila = Table.read_table("manila.csv")
print("Boston Table")
boston.show(4)
print("Manila Table")
manila.show(4)

**Question 1.** Use `np.arange` to create equal bins that start at 0 and have a uniform width of 5 ending just before 120.  

<!--
BEGIN QUESTION
name: q4_1
manual: true
-->
<!-- EXPORT TO PDF -->

In [ ]:
equal_bins = ...


# Don't delete the following lines!
boston.hist("ride time", bins = equal_bins)

plots.ylim(0, 0.05);

**Question 2.** Now, produce histograms of all ride times in Manila using the given bins.

<!--
BEGIN QUESTION
name: q4_2
manual: true
-->
<!-- EXPORT TO PDF -->

In [ ]:
manila...


# Don't delete the following line!
plots.ylim(0, 0.05);

**Question 3.** Assign `boston_under_10` and `manila_under_10` to the percentage of rides that are less than 10 minutes in their respective metropolitan areas. Use the height variables provided below in order to compute the percentages. Your solution should only use height variables, numbers, and mathematical operations. You should not access the tables boston and manila in any way.

<!--
BEGIN QUESTION
name: q4_3
manual: false
-->

In [ ]:
boston_under_5_height = 1.2
manila_under_5_height = 0.6
boston_5_to_under_10_height = 3.2
manila_5_to_under_10_height = 1.4

boston_under_10 = ...
manila_under_10 = ...

print(boston_under_10)
manila_under_10

Question 4. Let's take a closer look at the distribution of ride times in Manila. Assign manila_median_bin to an integer (1, 2, 3, or 4) that corresponds to the bin that contains the median time

1: 0-15 minutes
2: 15-40 minutes
3: 40-60 minutes
4: 60-80 minutes

Hint: The median of a sorted list has half of the list elements to its left, and half to its right

In [ ]:
manila.hist('ride time', bins = np.arange(0,120,15))
# Don't delete the following line!
plots.ylim(0, 0.05)
manila_median_bin = ...

**Question 5.** What is the main difference between the two histograms. What might be causing this?

**Hint:** Try thinking about external factors that may be causing the difference!

<!--
BEGIN QUESTION
name: q4_5
manual: true
-->
<!-- EXPORT TO PDF -->

*Write your answer here, replacing this text.*